### PR TITLE
add Japanese translation

### PR DESCRIPTION
**Pull request by n0bisuke**
I created japanae translation. if you don't mind, please merge this commit.

:D

### CODE REVIEW

**Comment by achingbrain** [comment]
This is amazing, thank you so much.  What's the purpose of the test.txt file?

**Comment by n0bisuke** [comment]
@achingbrain sorry, this is unnecessary file.

**Comment by n0bisuke** [comment]
Any update on this? ...

**Comment by achingbrain** [comment]
I've merged this because it's most excellent.

It looks like you've left a bunch of English text untranslated in the exercise files - for example in [remote_temperature/problem.ja.md](https://github.com/tableflip/nodebot-workshop/blob/master/exercises/remote_temperature/problem.ja.md), [robot_arm/problem.ja.md](https://github.com/tableflip/nodebot-workshop/blob/master/exercises/robot_arm/problem.ja.md) and [street_lamp/problem.ja.md](https://github.com/tableflip/nodebot-workshop/blob/master/exercises/street_lamp/problem.ja.md) the component description and hints at the bottom are still in English.  Any reason why?

**Pull request merged**
